repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^lib/'
      - id: end-of-file-fixer
        exclude: '^lib/'
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - refactor
          - perf
          - docs
          - test
          - chore
          - build
          - ci
          - style
          - release

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        files: '^src/.*\.(cpp|h)$'
        args: ['--style=file']

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        args:
          - '--suppress=missingInclude'
          - '--suppress=unusedFunction'
          - '--suppress=unmatchedSuppression'
          - '--suppress=toomanyconfigs'
          - '--suppress=unknownMacro'
          - '--enable=warning,style,performance'
          - '--inline-suppr'
          - '--std=c++17'
        files: '^src/.*\.(cpp|h)$'
