; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ulanzi

[env]
board_build.f_cpu = 240000000L
upload_speed = 115200
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
	bblanchon/ArduinoJson@^6.20.0
	evert-arias/EasyButton@2.0.1
	fastled/FastLED@3.10.3
	marcmerlin/FastLED NeoMatrix@^1.2
	knolleary/PubSubClient@^2.8
	densaugeo/base64@^1.4.0
	me-no-dev/ESPAsyncWebServer@^1.2.3
	me-no-dev/AsyncTCP@^1.1.1
	luisllamasbinaburo/MedianFilterLib@^1.0.0
	adafruit/Adafruit BME280 Library@^2.2.2
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit HTU21DF Library@^1.0.5
	adafruit/Adafruit SHT31 Library@^2.2.0
	maxgerhardt/ghostl
	https://github.com/QuentinCG/Arduino-Light-Dependent-Resistor-Library.git


[env:ulanzi]
platform = espressif32@6.3.0
framework = arduino
board = esp32dev
extra_scripts = pre:tools/build_web.py
board_build.partitions = svitrix_partition.csv
board_build.filesystem = littlefs
build_flags =
	-DULANZI
	-DMQTT_MAX_PACKET_SIZE=8192
	-D CORE_DEBUG_LEVEL=0
	-Wno-attributes
	-Os
	-fno-exceptions
	-Isrc/DisplayManager
	-Isrc/MatrixDisplayUi
	-Isrc/MQTTManager
	-Isrc/Apps
	-Isrc/ServerManager
	-Isrc/PeripheryManager
	-Isrc/MenuManager
	-Isrc/UpdateManager
	-Isrc/PowerManager
	-Isrc/Overlays
	; -DENABLE_GAMES
build_src_filter =
	+<*>
	-<Games/>
lib_deps =
	${env.lib_deps}

[env:native_test]
platform = native
build_flags =
	-std=c++17
	-DUNIT_TEST
	-I test/mocks
	-I lib/interfaces/src
	-I src/effects
	-I lib/MeanFilterLib/src
	-I src
test_framework = unity
test_filter = test_native/*
build_src_filter =
	-<*>
lib_deps =
lib_ignore =
	FastLED
	FastLED NeoMatrix
	PubSubClient
	ArduinoJson
	EasyButton
	ESPAsyncWebServer
	AsyncTCP
	MeanFilterLib
	MedianFilterLib
	Adafruit BME280 Library
	Adafruit BMP280 Library
	Adafruit HTU21DF Library
	Adafruit SHT31 Library
	ghostl
	Arduino-Light-Dependent-Resistor-Library
	TJpg_Decoder
	home-assistant-integration
	webserver
